---
title: "flowCore.Rmd"
output: html_document
date: "2024-03-03"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.align = "center")
```


```{r}
library(flowCore)
```


```{r}
file.name <- system.file("extdata","0877408774.B08", 
                         package="flowCore")
x <- read.FCS(file.name, transformation=FALSE)
summary(x)

keyword(x,c("$P1E", "$P2E", "$P3E", "$P4E"))

str(x@parameters)
x@parameters@varMetadata
x@parameters@data
```



```{r}

library(ggcyto)
# autoplot(x, "FL1-H", "FL2-H")

```







```{r}
## a sample file
fcsFile <- system.file("extdata", "0877408774.B08", package="flowCore")

## read file and linearize values
samp <-  read.FCS(fcsFile, transformation="linearize")
exprs(samp[1:3,])
summary(samp)

description(samp)[3:6]
class(samp)
class(samp@exprs)

## Only read in lines 2 to 5
subset <- read.FCS(fcsFile, which.lines=2:5, transformation="linearize")
exprs(subset)

## Read in a random sample of 100 lines
subset <- read.FCS(fcsFile, which.lines=100, transformation="linearize")
nrow(subset)
```




```{r, eval=FALSE}
browseVignettes( package = 'flowCore' )
```


```{r}
file.name <- system.file("extdata","0877408774.B08",
package="flowCore")
x <- read.FCS(file.name, transformation=FALSE)

library(ggcyto)
autoplot(x, "FL1-H", "FL2-H")

```







```{r}
library(ggcyto)
data(GvHD)
fs <- GvHD[subset(pData(GvHD), Patient %in%5:7 & Visit %in% c(5:6))[["name"]]]

#1d- density plot
#autoplot(fs, x = "SSC-H")

plot( fs@frames$s5a05)

```







```{r}
file.name <- system.file("extdata","0877408774.B08", package="flowCore")
x <- read.FCS(file.name, column.pattern="-H")

#autoplot(x, "FL1-H", "FL2-H")
```



```{r}
exprs(x)[1:3, ]

hist(x@exprs[, 'FL1-H'])

library(ggplot2)

my_dat <- as.data.frame(x@exprs)
my_dat[1:3, ]
#my_dat$`FL1-H`
# p <- ggplot( data = my_dat, mapping = aes( x = `FL1-H` ) )
p <- ggplot( data = my_dat[ my_dat$`FL1-H` >= 20, ], mapping = aes( x = `FL1-H` ) )
p + geom_histogram( binwidth = 1e1 )
p + geom_histogram( binwidth = 4 )
p + geom_histogram( binwidth = 4 ) + xlim(0, 1000)



p <- ggplot( data = my_dat, mapping = aes( x = `FL1-H`, y = `FL2-H` ) )
p + geom_point( col = "#00000008" )
p + geom_bin_2d()

p + geom_bin2d( bins = 30 )

p + geom_bin2d( bins = 100 )


p + geom_density_2d()
p + geom_density2d_filled( n = 2 )
p + geom_density2d_filled( h = c(0.20, 0.20) )
p + geom_density2d_filled( n=10, adjust = 50.9 )

```


