---
title: "What_is_an_fcs_file"
output: html_document
date: "2024-03-04"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Background

Flow Cytometry Standard (FCS)

https://isac-net.org/page/Data-Standards

https://en.wikipedia.org/wiki/Flow_Cytometry_Standard

Commercial software FlowJo: https://docs.flowjo.com/flowjo/

https://nanocellect.com/blog/what-is-flow-cytometry-light-scatter/


## flowcore

https://bioconductor.org/packages/release/bioc/html/flowCore.html


```{r}
library(flowCore)
```


```{r}
file.name <- system.file("extdata","0877408774.B08", 
                         package="flowCore")
x <- read.FCS(file.name, transformation=FALSE)
summary(x)

```



### meta data


```{r}
parameters(x)
pData(parameters(x))

```


### data


```{r}
exprs(x)[1:3,]

plot(exprs(x)[, 1])

# library(flowviz)

```



```{r}
library(ggplot2)
#library(wesanderson)

my_df <- as.data.frame(exprs(x))
my_df[1:3, ]
class(my_df$`FL1-A`)
#p <- ggplot( data = my_df, mapping = aes( x = `FSC-H` ) )
p <- ggplot( data = my_df, mapping = aes( x = `FL1-H` ) )
p + geom_histogram( binwidth = 10 )

p <- ggplot( data = my_df, mapping = aes( x = `FL1-H`, y = `FL2-H` ) )
p + geom_bin2d( binwidth = 10 ) + scale_fill_continuous(type = "viridis")


```





### analysis segment

Rarely used.


