---
title: "DESeq2"
output: html_document
date: "2025-07-09"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


https://bioconductor.org/packages/release/bioc/html/DESeq2.html



```{r}
#library("DESeq2")
pasCts <- system.file("extdata",
                      "pasilla_gene_counts.tsv.gz",
                      package="DESeq2", mustWork=TRUE)
pasAnno <- system.file("extdata",
                       "pasilla_sample_annotation.csv",
                       package="DESeq2", mustWork=TRUE)

#pasCts <- "/home/knausb/R/x86_64-pc-linux-gnu-library/4.5/DESeq2/extdata/pasilla_gene_counts.tsv.gz"
#pasAnno <- "/home/knausb/R/x86_64-pc-linux-gnu-library/4.5/DESeq2/extdata/pasilla_sample_annotation.csv"

cts <- as.matrix(read.csv(pasCts,sep="\t",row.names="gene_id"))
coldata <- read.csv(pasAnno, row.names=1)
coldata <- coldata[,c("condition","type")]
coldata$condition <- factor(coldata$condition)
coldata$type <- factor(coldata$type)

rownames(coldata) <- sub("fb", "", rownames(coldata))
all(rownames(coldata) %in% colnames(cts))

all(rownames(coldata) == colnames(cts))

cts <- cts[, rownames(coldata)]
all(rownames(coldata) == colnames(cts))

coldata
#row.names(cts) <- NULL
cts[1:3, ]

#sessionInfo()

library("DESeq2")
print("DESeq2 loaded")
#
setClassUnion("ExpData", c("matrix", "SummarizedExperiment"))
dds <- DESeqDataSetFromMatrix(countData = cts,
                              colData = coldata,
                              design = ~ condition)
#, NAMES = NULL)
dds

dds@NAMES

#save(dds, file = "dds.RData")

```



```{r}
smallestGroupSize <- 3
keep <- rowSums(counts(dds) >= 10) >= smallestGroupSize
dds <- dds[keep,]
```


```{r}
dds$condition <- relevel(dds$condition, ref = "untreated")

dds <- DESeq(dds)
res <- results(dds)
res

#res <- results(dds, name="condition_treated_vs_untreated")
res <- results(dds, contrast=c("condition","treated","untreated"))

```





