---
title: "Untitled"
output: html_document
date: "2025-08-21"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Pasilla example


```{r}
## ----loadPasilla--------------------------------------------------------------
library("DESeq2")
pasCts <- system.file("extdata",
                      "pasilla_gene_counts.tsv.gz",
                      package="DESeq2", mustWork=TRUE)
pasAnno <- system.file("extdata",
                       "pasilla_sample_annotation.csv",
                       package="DESeq2", mustWork=TRUE)
cts <- as.matrix(read.csv(pasCts,sep="\t",row.names="gene_id"))
coldata <- read.csv(pasAnno, row.names=1)
coldata <- coldata[,c("condition","type")]
coldata$condition <- factor(coldata$condition)
coldata$type <- factor(coldata$type)

## ----showPasilla--------------------------------------------------------------
head(cts,2)
coldata

## ----reorderPasila------------------------------------------------------------
rownames(coldata) <- sub("fb", "", rownames(coldata))
all(rownames(coldata) %in% colnames(cts))
all(rownames(coldata) == colnames(cts))
cts <- cts[, rownames(coldata)]
all(rownames(coldata) == colnames(cts))

## ----matrixInput--------------------------------------------------------------
library("DESeq2")
cts[1:3, ]
coldata[1:3, ]

#setClassUnion("ExpData", c("matrix", "SummarizedExperiment"))
dds <- DESeqDataSetFromMatrix(countData = cts,
                              colData = coldata,
                              design = ~ condition)
dds

## ----addFeatureData-----------------------------------------------------------
#featureData <- data.frame(gene=rownames(cts))
#featureData[1:3, , drop = F]
#mcols(dds) <- DataFrame(mcols(dds), featureData)
#mcols(dds)
```


```{r}
dds <- DESeq(dds)
res <- results(dds)
res
```


```{r}
gene <- "FBgn0000370"
plotCounts(dds, gene = gene)

```



```{r}
class(dds)
str(dds)

normalized=TRUE
#normalized=FALSE
replaced=FALSE

gene <- "FBgn0000370"

cnts <- counts(dds,normalized=normalized,replaced=replaced)
cnts[1:3, ]
class(cnts)
#[gene,]

```





```{r}

cnts <- cnts[ "FBgn0000370", ]
class(cnts)

cnts <- data.frame( Counts = cnts, Condition = names(cnts) )
cnts[1:3, ]

cnts$Condition2 <- sub("[[:digit:]]$", "", cnts$Condition)
cnts$Condition2 <- as.factor(cnts$Condition2)
cnts[1:3, ]

library(ggplot2)

p <- ggplot(data = cnts, mapping = aes( x = Condition2, y = Counts, fill = Condition2) )
p <- p + geom_boxplot()
p <- p + geom_jitter( size = 4, width = 0.1 )
p <- p + theme_bw()
p <- p + theme(legend.position="none")
p <- p + theme(axis.title.y=element_blank())
p <- p + theme(axis.title.x=element_blank())
p <- p + ggtitle( "Gene: FBgn0000370" )
p
```


```{r}
library(ggpubr)

ggarrange(p, p, labels = c("A", "B"))

ggarrange(p, p, labels = c("A", "B"), ncol = 1)

ggarrange(p, p, p, p, p, p, p, p, labels = c("A", "B"), ncol = 4, nrow=2)

```


