---
title: "DESeq2 example"
output: html_document
date: "2025-08-15"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
pasCts <- system.file("extdata",
                      "pasilla_gene_counts.tsv.gz",
                      package="DESeq2", mustWork=TRUE)
cts <- as.matrix(read.csv(pasCts,sep="\t",row.names="gene_id"))
cts[1:3, ]

# Example with a column of gene names.
cts2 <- data.frame(Gene=rownames(cts), cts)
row.names(cts2) <- NULL
cts2[1:3, ]
# 
row.names(cts2) <- cts2$Gene
cts2 <- cts2[ , -1]
cts2 <- as.matrix(cts2)
cts2[1:3, ]
class(cts2)
```



```{r}
pasAnno <- system.file("extdata",
                       "pasilla_sample_annotation.csv",
                       package="DESeq2", mustWork=TRUE)
coldata <- read.csv(pasAnno, row.names=1)
coldata <- coldata[,c("condition","type")]
coldata$condition <- factor(coldata$condition)
coldata$type <- factor(coldata$type)
coldata[1:3, ]

rownames(coldata) <- sub("fb", "", rownames(coldata))
all(rownames(coldata) %in% colnames(cts))

all(rownames(coldata) == colnames(cts))
cts <- cts[, rownames(coldata)]
all(rownames(coldata) == colnames(cts))

```



```{r}
# colnames(cts2) <- paste("X", 1:ncol(cts2), sep = "")
# cts2[1:3, ]
# colnames(cts2) <- sub("X", "Tree", colnames(cts2))
# cts2[1:3, ]
```



```{r}
library("DESeq2")
cts[1:3, ]
coldata[1:3, ]
dds <- DESeqDataSetFromMatrix(countData = cts,
                              colData = coldata,
                              design = ~ condition)
dds

```




