---
title: "BUSCO linemap"
output: html_document
date: "2023-08-08"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


- https://tidyr.tidyverse.org/articles/pivot.html
- https://posit.co/resources/cheatsheets/


## DM6


```{r}
t1 <- Sys.time()
dm6 <- read.table("DM6_full_table.tsv", header = FALSE, sep = "\t", fill = TRUE)
names(dm6) <- c("Busco_id", "Status", "Sequence", "Gene_Start", "Gene_End", "Strand", "Score", "Length")
dm6[1:3, ]
table(dm6$Status)

dm6 <- dm6 |> dplyr::filter( Status == "Complete")
table(dm6$Status)
```


## DM4


```{r}
dm4 <- read.table("DM4_full_table.tsv", header = FALSE, sep = "\t", fill = TRUE)
names(dm4) <- c("Busco_id", "Status", "Sequence", "Gene_Start", "Gene_End", "Strand", "Score", "Length")
dm4[1:3, ]

dm4 <- dm4 |> dplyr::filter( Status == "Complete")
table(dm4$Status)

```


## Castle-Russet


```{r}
casr <- read.table("castle-russet_full_table.tsv", header = FALSE, sep = "\t", fill = TRUE)
names(casr) <- c("Busco_id", "Status", "Sequence", "Gene_Start", "Gene_End", "Strand", "Score", "Length")
table(casr$Status)

casr[1:3, ]
```



## chr3


```{r}

table(dm6$Sequence)
chr3 <- dm6[ dm6$Sequence == "chr03", ]

row.names(chr3) <- chr3$Busco_id
chr3[1:3, ]
chr3[c("265at71240", "383at71240"), ]


table(dm4$Sequence)
tmp <- dm4[ dm4$Sequence == "ST4.03ch03", ]
row.names(tmp) <- tmp$Busco_id
tmp[1:3, ]


tmp[ chr3$Busco_id[1:4], ]

chr3 <- cbind(chr3, tmp[ chr3$Busco_id, "Gene_Start"])
colnames(chr3)[ncol(chr3)] <- "dm4"
chr3[1:3, ]


table(casr$Sequence)
tmp <- casr[ casr$Sequence == "chr03_0", ]
tmp <- tmp[ !duplicated(tmp$Busco_id), ]
#tmp <- tmp |> dplyr::filter( Status == "Complete")
row.names(tmp) <- tmp$Busco_id
#tmp[1:3, ]
#nrow(tmp)
chr3 <- cbind(chr3, tmp[ chr3$Busco_id, "Gene_Start"])
colnames(chr3)[ncol(chr3)] <- "chr03_0"
chr3[1:3, ]

tmp <- casr[ casr$Sequence == "chr03_1", ]
#tmp <- tmp |> dplyr::filter( Status == "Complete")
tmp <- tmp[ !duplicated(tmp$Busco_id), ]
row.names(tmp) <- tmp$Busco_id
chr3 <- cbind(chr3, tmp[ chr3$Busco_id, "Gene_Start"])
colnames(chr3)[ncol(chr3)] <- "chr03_1"

tmp <- casr[ casr$Sequence == "chr03_2", ]
#tmp <- tmp |> dplyr::filter( Status == "Complete")
tmp <- tmp[ !duplicated(tmp$Busco_id), ]
row.names(tmp) <- tmp$Busco_id
chr3 <- cbind(chr3, tmp[ chr3$Busco_id, "Gene_Start"])
colnames(chr3)[ncol(chr3)] <- "chr03_2"

tmp <- casr[ casr$Sequence == "chr03_3", ]
#tmp <- tmp |> dplyr::filter( Status == "Complete")
tmp <- tmp[ !duplicated(tmp$Busco_id), ]
row.names(tmp) <- tmp$Busco_id
chr3 <- cbind(chr3, tmp[ chr3$Busco_id, "Gene_Start"])
colnames(chr3)[ncol(chr3)] <- "chr03_3"

tmp <- casr[ casr$Sequence == "chr03_4", ]
#tmp <- tmp |> dplyr::filter( Status == "Complete")
tmp <- tmp[ !duplicated(tmp$Busco_id), ]
row.names(tmp) <- tmp$Busco_id
chr3 <- cbind(chr3, tmp[ chr3$Busco_id, "Gene_Start"])
colnames(chr3)[ncol(chr3)] <- "chr03_4"

chr3[1:3, ]

```






## Line map


```{r}




```



## Plot 2


```{r}

busc <- chr3[, c(1, 4, 9:ncol(chr3))]
names(busc)[2] <- "dm6"
busc[1:3, ]

library(tidyr)
library(dplyr)

#col_no <- 21
#rm(data_long)
#vars <- colnames(busc)[1:col_no]
vars <- colnames(busc)

#data_long <- busc[, 1:col_no] %>% 
#  pivot_longer( cols = 2:col_no )

data_long <- busc %>%
  select(all_of(vars)) %>% 
  pivot_longer( cols = vars[-1] )

names(data_long)[2:3] <- c("Sample", "POS")
data_long$Sample <- factor(data_long$Sample , levels = unique(data_long$Sample))
data_long

library(ggplot2)
p <- ggplot(data_long, aes(x = Sample, y = POS, color = Busco_id, group = Busco_id)) + 
  geom_point( size = 1.2 ) +
  geom_line( linewidth = 0.8 )
p <- p + scale_color_manual( values = rep(viridisLite::magma( n = 8, alpha = 0.8 ), times = 1e6) )
p <- p + theme_bw()
#p <- p + xlab("")
p <- p + ylab("Position (Mbp)")
p <- p + theme(legend.position = "none")
p <- p + theme(axis.title.x = element_blank(), 
               axis.text.x = element_text(angle = 60, hjust = 1, size = 12))
p <- p + scale_y_continuous( breaks = seq(0, 1e9, by = 10e6),
                        labels = seq(0, 1e9, by = 10e6)/1e6,
                        minor_breaks = seq(0, 1e9, by = 5e6) )
p <- p + ggtitle( label = "BUSCO positions: Chromosome 3" )
```


```{r, fig.width=10, fig.height=6}
p
```


## Process assembly as unknown


```{r}
dm6[1:3, ]
casr[1:3, ]
casr$Sequence[casr$Sequence == ""] <- "Unplaced"
table(casr$Sequence)

# Create a list where each element is one 'Sequence'.
seq_list <- vector(mode = "list", length = length(unique(casr$Sequence)))
names(seq_list) <- unique(casr$Sequence)
for(i in 1:length(seq_list)){
  seq_list[[i]] <- casr[ casr$Sequence == names(seq_list)[i], ]
  seq_list[[i]] <- seq_list[[i]][ !duplicated(seq_list[[i]]$Busco_id), ]
  row.names( seq_list[[i]] ) <- seq_list[[i]]$Busco_id
}

barplot( sort( unlist(lapply(seq_list, nrow)), decreasing = TRUE )[1:24], las = 3 )


busc_df <- matrix(nrow = length(seq_list) + 1, ncol = length(unique(dm6$Sequence)))
colnames(busc_df) <- unique(dm6$Sequence)
row.names(busc_df) <- c( "DM6", names(seq_list))
busc_df[1, ] <- table(dm6$Sequence)
busc_df[1:3, ]

# Loop over unknown sequences.
for(i in 1:length(seq_list)){
  tmp <- seq_list[[i]]
  for(j in 1:ncol(busc_df)){
    # Loop over seed sequences.
    #tmp[c("171360at71240", "171360at71241"), ]
    chrom_BUSCOs <- dm6$Busco_id[ dm6$Sequence == colnames(busc_df)[j] ]
    tmp2 <- tmp[ chrom_BUSCOs, ]
    tmp2 <- tmp2[ !is.na(tmp2$Busco_id), ]
    busc_df[ names(seq_list)[i], j] <- nrow(tmp2)
  }
}




# # Loop over unknown sequences.
# for(i in 2:nrow(busc_df)){
#   tmp <- seq_list[[i - 1]]
#   for(j in 1:ncol(busc_df)){
#     # Loop over seed sequences.
#     #tmp[c("171360at71240", "171360at71241"), ]
#     tmp2 <- tmp[ dm6$Busco_id[ dm6$Sequence == colnames(busc_df)[j] ][1:10], ]
#     tmp2 <- tmp2[ !is.na(tmp2$Busco_id), ]
#     busc_df[i, j] <- nrow(tmp2)
#   }
# }




```


```{r, fig.width=10, fig.height=10}
vcfR::heatmap.bp(busc_df[-1, ])
```


```{r}
busc_df[ busc_df[, 1] > 0, ]
busc_df[ busc_df[, 2] > 0, ]
busc_df[ busc_df[, 3] > 0, ]
busc_df[ busc_df[, 4] > 0, ]

busc_df2 <- sweep(busc_df[-1, ], MARGIN = 2, STATS = busc_df[1, ], FUN = "/")
busc_df2[ busc_df2[, 1] > 0.1, ]

busc_df[1:6, ]
busc_df2[1:6, ]
```


```{r}
busc_df[ busc_df[, 3] > 0, ]
table(table(casr$Busco_id[ casr$Sequence == "chr01_1" ]))

sort(table(intersect( dm6$Busco_id[ dm6$Sequence == "chr01" ], 
           casr$Busco_id[ casr$Sequence == "chr01_1" ] )), decreasing = TRUE)[1:10]

```



```{r}
t99 <- Sys.time()
t99 - t1
```

