---
title: "DM6 comp"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 2
date: "2023-08-21"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
#
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_chunk$set(echo = FALSE)
#knitr::opts_chunk$set(results = "hide")
knitr::opts_chunk$set(fig.align = "center")
```


## Load functions

```{r}
t1 <- Sys.time()
#source("../../hemp_busco_chrom/Rfunctions.R")
#source("~/gits/ViningLab_code/busco_lineplot/Rfunctions.R")
source("Rfunctions.R")
```


## Set min_BUSCO


```{r, include=TRUE, results='asis'}
my_min_BUSCO <- 2
paste("min_BUSCO:", my_min_BUSCO)
```



## Load Known or Seed 


```{r}
#busc <- read_busco("DM_6_busco/full_table.tsv")
busc <- read_busco("DM6_full_table.tsv")
```


```{r}
p <- busco_bar(busc, max_copy = NULL)
#p <- busco_bar(busc, max_copy = 3)
p <- p + ggtitle("BUSCO: DM6")
p
```



Sort by chromosome into a list


```{r}
my_bl <- make_known(busc)
lapply( my_bl[1:3], function(x){x[1:2, ]} )
```



## Load Unknown


```{r}
#busc <- read_busco("ATL_busco/full_table.tsv")
busc <- read_busco("atlantic_full_table.tsv")
busc[1:3, ]
```


```{r}
p <- busco_bar(busc)
#p <- busco_bar(busc, max_copy = 6)
p <- p + ggtitle("BUSCO: Atlantic")
p
```


## Add unknown to seed



```{r}
lapply( my_bl[1:3], function(x){x[1:2, ]} )

my_bl <- add_unknown(my_bl, busc)

lapply( my_bl[1:3], function(x){x[1:2, ]} )
```


## Nudge, flip, min threshold


```{r}
my_bl <- position_BUSCOS(my_bl, min_BUSCO = my_min_BUSCO, sort_by = "max_busco")
```


## Name the list


```{r}
my_bl_atl <- my_bl
```


## Castle-Russet


```{r}
#busc <- read_busco("DM_6_busco/full_table.tsv")
busc <- read_busco("DM6_full_table.tsv")
my_bl <- make_known(busc)
#busc <- read_busco("ATL_busco/full_table.tsv")
#busc <- read_busco("castle_russet/full_table.tsv")
busc <- read_busco("castle-russet_full_table.tsv")
#busc[1:3, ]
```


```{r}
p <- busco_bar(busc)
#p <- busco_bar(busc, max_copy = 6)
#p <- p + ggtitle("BUSCO: Atlantic")
p <- p + ggtitle("BUSCO: Castle-Russet")
p
```



```{r}
#lapply( my_bl[1:3], function(x){x[1:2, ]} )

my_bl <- add_unknown(my_bl, busc)

#lapply( my_bl[1:3], function(x){x[1:2, ]} )
```


## Nudge, flip, min threshold


```{r}
#my_bl <- position_BUSCOS(my_bl, sort_by = "max_pos")
#
my_bl <- position_BUSCOS(my_bl, min_BUSCO = my_min_BUSCO, sort_by = "max_busco")

```


## Plot


```{r}
#for(i in 1:length(busco_l)){
for(i in 1:length(my_bl)){
  tmp <- my_bl[[i]]
  colnames(tmp)[9:ncol(tmp)] <- paste("CR:", colnames(tmp)[9:ncol(tmp)], sep = "")
  #tmp[1:3, ]
  rownames(tmp) <- tmp$Busco_id
  tmp <- tmp[ , c(4, 9:ncol(tmp))]
  colnames(tmp)[ colnames(tmp) == "Gene_Start" ] <- paste("DM6:", names(my_bl)[i], sep = "")
  #tmp[1:3, ]
  
  tmp2 <- my_bl_atl[[i]]
  colnames(tmp2)[9:ncol(tmp2)] <- paste("ATL:", colnames(tmp2)[9:ncol(tmp2)], sep = "")
  tmp <- cbind( tmp2[ , ncol(tmp2):9 ], tmp )
  
  #p <- gg_line_map(tmp)
  p <- gg_line_map(tmp, rect = TRUE, palpha = 1, size = 2.2, 
                   lalpha = 0.1, linewidth = 1.4, line_na_rm = TRUE)
  p <- p + ggtitle( paste("Chromosome:", names(my_bl)[i]) )
  print(p)
}
```



```{r}
t99 <- Sys.time()
t99 - t1
```


