---
title: "Ideograms"
output: html_document
date: "2023-04-11"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.align = "center")
```


## Load data


```{r}
nucs <- read.csv("EH23b.softmasked_nuccomp.csv")
# Subset to a reasonable number of sequences.
nucs <- nucs[1:10, ]

nucs[1:3, ]
nucs$chrom_num <- sub(".+chr", "", nucs$Id)
nucs$chrom_num[nucs$chrom_num == "X"] <- 10
nucs$chrom_num <- as.numeric(nucs$chrom_num)
nucs[1:3, ]
```


```{r}
library(ggplot2)

chrom_wid <- 0.1

#p <- ggplot( data = nucs, mapping = aes( x = chrom_num, y = Length ))
p <- ggplot( )
p <- p + theme_bw()
p <- p + geom_rect( 
  data = nucs, 
  aes( xmin = chrom_num - chrom_wid,
       xmax = chrom_num + chrom_wid,
       ymin = 1, ymax = Length),
  fill = "#DCDCDC",
  color = "#000000"
)

p

```


```{r}
# Theme
p <- p + scale_x_continuous( 
  breaks = nucs$chrom_num,
  labels = nucs$Id
)
p

p <- p + scale_y_continuous(
  breaks = seq( 0, 120e6, by = 10e6), 
  labels = seq( 0, 120, by = 10)
)
p

p <- p + ggplot2::theme( 
    panel.grid.minor.x = ggplot2::element_line( linewidth = 0.4, color = "#C0C0C0", linetype = 3 ),
    axis.text.x = element_text(angle = 60, hjust = 1),
    axis.title.x=element_blank(),
    panel.grid.major.y = ggplot2::element_line( linewidth = 0.4, color = "#C0C0C0", linetype = 1 ),
    panel.grid.minor.y = ggplot2::element_line( linewidth = 0.4, color = "#C0C0C0", linetype = 3 )
  )
p

p <- p + ggplot2::ylab("Position (Mbp)")
p <- p + ggtitle( "EH23b" )

p
```


## Add windowed data


```{r}
wins <- read.table("EH23b.softmasked_CG_wins.bed", sep = "\t")
colnames(wins) <- c('chrom', 'chromStart', 'chromEnd', 'name', 'score', 'strand', 'thickStart', 'thickEnd', 'itemRGB', 'blockCount', 'blockSizes')
wins[1:3, ]
```


```{r}
wins$chrom_num <- sub(".+chr", "", wins$chrom)
wins$chrom_num[ wins$chrom_num == "X" ] <- 10
wins$chrom_num <- as.numeric(wins$chrom_num)
wins[1:3, ]

wins$col <- unlist(lapply(strsplit(wins$itemRGB, split = ","), function(x){ rgb(as.numeric(x[1])/255, as.numeric(x[2])/255, as.numeric(x[3])/255)}))
wins[1:3, ]
#table(wins$chrom_num)
```


```{r}

#p <- 
p + geom_rect( 
  data = wins, 
  aes( xmin = chrom_num - (1 - (score/1e3)) / 3,
       xmax = chrom_num + (1 - (score/1e3)) / 3,
       ymin = chromStart, ymax = chromEnd),
  #fill = "#1E90FF",
  fill = wins$col,
  #color = "#000000"
  color = NA
)


```



