---
title: "CHROM plot"
output: html_document
date: "2023-04-04"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Data input

```{r}
t1 <- Sys.time()
#EH23a <- read.csv("../../CannabisPangenome/FigureSideo/EH23a.softmasked_nuccomp.csv")
EH23a <- read.csv("../ideograms/EH23b.softmasked_nuccomp.csv")

EH23a$chrom_num <- sub(".+chr", "", EH23a$Id)
EH23a$chrom_num[ EH23a$chrom_num == "X" ] <- 10
EH23a$chrom_num <- as.numeric(EH23a$chrom_num)
EH23a[1:3, ]
```


Plot


```{r}
library(ggplot2)

chrom_wid <- 0.05
chrom_offset <- 0.0

p <- ggplot2::ggplot()
p <- p + theme_bw()
p <- p + ggplot2::geom_rect( 
  data = EH23a,
  mapping = ggplot2::aes( xmin = chrom_num - chrom_wid - chrom_offset,
                xmax = chrom_num + chrom_wid - chrom_offset,
                ymin = 1, ymax = Length),
  fill = "#DCDCDC",
  color = "#000000"
)

p

```


```{r}
# Theme
p <- p + ggplot2::scale_x_continuous( 
  breaks = EH23a$chrom_num,
#  limits = c(0.6, 10.4),
#  limits = c(0.5, 10.5),
#  labels = EH23a$Id
  labels = sub("a.chr", ".chr", EH23a$Id)
)
  
p <- p + scale_y_continuous(
  breaks = seq( 0, 120e6, by = 10e6), 
  labels = seq( 0, 120, by = 10)
)

#  p <- p + ggplot2::theme_bw() + 
p <- p + ggplot2::theme( 
      #      panel.grid.minor.x = ggplot2::element_blank(), 
    panel.grid.minor.x = ggplot2::element_line( linewidth = 0.4, color = "#C0C0C0", linetype = 3 ),
    axis.text.x = element_text(angle = 60, hjust = 1),
    axis.title.x=element_blank(),
    panel.grid.major.y = ggplot2::element_line( linewidth = 0.4, color = "#C0C0C0", linetype = 1 ),
    panel.grid.minor.y = ggplot2::element_line( linewidth = 0.4, color = "#C0C0C0", linetype = 3 )
  )
  
p <- p + ggplot2::ylab("Position (Mbp)")
p <- p + ggtitle( "A) EH23" )

p

p + xlim(1.6, 4)
#+ ylim(30e6, 40e6)


```



```{r}

my_dat <- data.frame(
#  my_x = rep( unique(EH23a$Id), times = 2 ),
  my_x = rep( 1:10, times = 2 ),
  my_y = rnorm( n = 20, mean = 40e6, sd = 10e6),
  #my_bg = rep("#B2222266", times = 20)
  my_bg = rep(c("#B2222266", "#1E90FF"), times = 10)
)

#p + geom_point( data = my_dat, mapping = aes( x = my_x, y = my_y, fill = my_bg), shape = 21, size = 8)
p + geom_point( data = my_dat, mapping = aes( x = my_x, y = my_y, fill = my_bg), fill = my_dat$my_bg, shape = 21, size = 8)

```




