---
title: "topGO"
output: html_document
date: "2023-08-28"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
# library(topGO)
# ?topGOdata-class
# data(GOdata)
#str(GOdata)
```




```{r}
# library(topGO)
# #library(package = affyLib, character.only = TRUE)
# data(geneList)
# library(package = affyLib, character.only = TRUE)

```




```{r}
###################################################
### code chunk number 6: topGO.Rnw:165-169
###################################################
library(topGO)
library(ALL)
data(ALL)
data(geneList)
library(package = affyLib, character.only = TRUE)


###################################################
### code chunk number 7: topGO.Rnw:179-181
###################################################
#affyLib <- paste(annotation(ALL), "db", sep = ".")
#library(package = affyLib, character.only = TRUE)


#library("hgu95av2.db")
#select()

#library("org.Hs.eg.db")

###################################################
### code chunk number 8: topGO.Rnw:191-192
###################################################
sum(topDiffGenes(geneList))


###################################################
### code chunk number 9: topGO.Rnw:199-204
###################################################
sampleGOdata <- new("topGOdata", 
                    description = "Simple session", ontology = "BP",
                    allGenes = geneList, geneSel = topDiffGenes,
                    nodeSize = 10,
                    annot = annFUN.db, affyLib = affyLib)

```




```{r}
sampleGOdata

class(geneList)
geneList[1:4]
hist(geneList)


topDiffGenes

?topGOdata-class
?topGO
```




```{r}

#length(geneList)

set.seed(99)
thingyList <- runif(n = 100, min = 0, max = 1)
# Add some significant values.
set.seed(99)
thingyList <- c(thingyList, runif(n = 10, min = 0, max = 0.05))
#thingyList
# Fabricated names do not appear to work.
#names(thingyList) <- paste("paulsThingy_", 1:length(thingyList), sep = "")
# Re-using the example names appears to work.
names(thingyList) <- names(geneList)[1:length(thingyList)]

thingyList
class(thingyList)
hist(thingyList)


sampleGOdata <- new("topGOdata", 
                    description = "Simple session", ontology = "BP",
                    #allGenes = geneList,
                    allGenes = thingyList,
                    geneSel = topDiffGenes,
                    nodeSize = 10,
                    annot = annFUN.db, affyLib = affyLib)
sampleGOdata


```



