---
title: "Scale independence"
output: 
  html_document:
    toc: true
    code_folding: show
date: "2023-03-31"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.align = "center")
```


## Load data


```{r}
t1 <- Sys.time()
expData <- read.table(file = "W103first200.tsv", header = TRUE, sep  ="\t")
expData[1:3, 1:8]
#nrow(expData)
#ncol(expData) - 4

datExpr <- expData[, -c(1:4)]
expData <- expData[, 1:4]
#expData[1:3, ]

#names(datExpr) <- paste("Sample", 1:ncol(datExpr), sep  ="")
names(datExpr) <- paste("Sample", sub("^X", "", colnames(datExpr)), sep = "")
rownames(datExpr) <- expData$ID
datExpr <- t(datExpr)
```


## WGCNA


```{r, message=FALSE}
library(WGCNA)
```


```{r}
# Choose a set of soft-thresholding powers
powers = c(c(1:10), seq(from = 12, to=20, by=2))
# Call the network topology analysis function
enableWGCNAThreads(nThreads = 2)
sft = pickSoftThreshold(datExpr, powerVector = powers, verbose = 5)

# Plot the results:
#sizeGrWindow(9, 5)
par(mfrow = c(1,2))
cex1 = 0.9
# Scale-free topology fit index as a function of the soft-thresholding power
plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
main = paste("Scale independence"));
text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
labels=powers,cex=cex1,col="red");
# this line corresponds to using an R^2 cut-off of h
abline(h=0.90,col="red")
# Mean connectivity as a function of the soft-thresholding power
plot(sft$fitIndices[,1], sft$fitIndices[,5],
xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n",
main = paste("Mean connectivity"))
text(sft$fitIndices[,1], sft$fitIndices[,5], labels=powers, cex=cex1,col="red")
par(mfrow = c(1,1))
```


```{r}
# Choose a set of soft-thresholding powers
# powers = c(c(1:10), seq(from = 12, to=20, by=2))
powers = c(c(1:10), seq(from = 12, to=100, by=2))
# Call the network topology analysis function
enableWGCNAThreads(nThreads = 2)
sft = pickSoftThreshold(datExpr, powerVector = powers, verbose = 0)


# Plot the results:
#sizeGrWindow(9, 5)
par(mfrow = c(1,2))
cex1 = 0.9
# Scale-free topology fit index as a function of the soft-thresholding power
plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
main = paste("Scale independence"));
text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
labels=powers,cex=cex1,col="red");
# this line corresponds to using an R^2 cut-off of h
abline(h=0.90,col="red")
# Mean connectivity as a function of the soft-thresholding power
plot(sft$fitIndices[,1], sft$fitIndices[,5],
xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n",
main = paste("Mean connectivity"))
text(sft$fitIndices[,1], sft$fitIndices[,5], labels=powers, cex=cex1,col="red")
par(mfrow = c(1,1))
```




