---
title: "GeneMapper output conversion"
output: 
  html_document:
    toc: true
    toc_depth: 2
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data input


```{r}
#if( Sys.info()['sysname'] == "Linux" ){}
if( Sys.info()['sysname'] == "Windows" ){
  setwd("C:/Users/smithai3/Desktop/New folder/")  
}

my_infile <- "Essex_project23_Plate17Table.txt"
my_data <- read.table(my_infile, sep = "\t", header = TRUE, stringsAsFactors = FALSE, quote = "")

#my_data <- read.table("SX_Project23_Plate18 Genotypes Table.txt", sep = "\t", header = TRUE, stringsAsFactors = FALSE)
#my_data <- read.table("SX_Project23_Plate18 Table.txt", sep = "\t", header = TRUE, stringsAsFactors = FALSE)
#my_data <- read.table("D:/Essex_project23_Plate17 Genotypes Table.txt", sep = "\t", header = TRUE, stringsAsFactors = FALSE, quote = "")
#my_data <- read.table("EssexProject_23 Genotypes Table.txt", sep = "\t", header = TRUE, stringsAsFactors = FALSE, quote = "")
#my_data <- read.table("SX_ProjectPlate6 Genotypes Table.txt", sep = "\t", header = TRUE, stringsAsFactors = FALSE, quote = "")
#my_data <- read.table("Plate 7 Genotypes Table.txt", sep = "\t", header = TRUE, stringsAsFactors = FALSE, quote = "")
#my_data <- read.table("Plate 8 Genotypes Table.txt", sep = "\t", header = TRUE, stringsAsFactors = FALSE, quote = "")
#my_data <- read.table("Plate 9 Genotypes Table.txt", sep = "\t", header = TRUE, stringsAsFactors = FALSE, quote = "")
#my_data <- read.table("Plate 10 Genotypes Table.txt", sep = "\t", header = TRUE, stringsAsFactors = FALSE, quote = "")
#my_data <- read.table("Plate 11 Genotypes Table.txt", sep = "\t", header = TRUE, stringsAsFactors = FALSE, quote = "")
#my_data <- read.table("Plate12 Genotypes Table.txt", sep = "\t", header = TRUE, stringsAsFactors = FALSE, quote = "")
#my_data <- read.table("Plate13 Genotypes Table.txt", sep = "\t", header = TRUE, stringsAsFactors = FALSE, quote = "")
#my_data <- read.table("Plate14 Genotypes Table.txt", sep = "\t", header = TRUE, stringsAsFactors = FALSE, quote = "")
my_data[1:3, 1:6]
nrow(my_data)

my_data[960, 1:6]
my_data[1:3, 6:19]

table(my_data$Marker)
unique(my_data$Marker)

marker_list <- vector( mode = "list", length = length(unique(my_data$Marker)) )
names(marker_list) <- unique(my_data$Marker)
length(marker_list)
```


## Organize data


```{r}
grep("^Allele", colnames(my_data), value =T)

for(j in 1:length(marker_list)){
  my_marker <- my_data[ my_data$Marker == names(marker_list)[j], ]

  # Determine allele names/sizes
  my_alleles_tbl <- my_marker[ , grep("^Allele", colnames(my_marker))]
  #my_alleles[1:3, ]
  my_alleles <- unique(unlist(my_alleles_tbl))
  my_alleles <- my_alleles[ my_alleles != "?" ]
  my_alleles <- my_alleles[ my_alleles != "" ]
  my_alleles <- my_alleles[!is.na(my_alleles)]
  my_alleles <- sort(as.numeric(my_alleles))

  # Initialize a new data.frame for output.
  my_df <- data.frame( matrix( nrow = nrow(my_marker), ncol = length(my_alleles)) )
  names(my_df) <- my_alleles
  #row.names(my_df) <- my_data$Sample.Name
  row.names(my_df) <- my_marker$Sample.Name
  #my_df[1:3, ]

  # Isolate peak sizes/calls.
  #my_peaks <- my_data[ , grep("^Allele", colnames(my_data))]
  my_peaks <- my_marker[ , grep("^Allele", colnames(my_marker))]
  #my_peaks[1:3, ]
  # nrow(my_peaks)

  # Populate data.frame with allele calls.

  for(i in 1:nrow(my_df)){
    my_calls <- my_peaks[i, ]
    my_calls <- my_calls[ my_calls != "?" ]
    my_calls <- my_calls[ my_calls != "" ]
    my_calls <- my_calls[!is.na(my_calls)]
    my_calls <- unique(my_calls)
    my_df[ i, my_calls ] <- my_calls
  }

  my_df[is.na(my_df)] <- 0
  names(my_df) <- paste("Allele_", names(my_df), sep = "")

  #my_df[1:6, ]
  marker_list[[j]] <- my_df
}

lapply(marker_list[1:3], function(x){ x[1:3, 1:3] })
length(marker_list)
```


## Write to file.


```{r}
j <- 1
tmp <- marker_list[[j]]
names(tmp) <- sub("Allele_", paste(names(marker_list)[j], ":", sep = ""), names(tmp))
out_df <- tmp

names(marker_list)
for(j in 2:length(marker_list)){
  tmp <- marker_list[[j]]
  #names(tmp) <- sub("Allele", names(marker_list)[j], names(tmp))
  names(tmp) <- sub("Allele_", paste(names(marker_list)[j], ":", sep = ""), names(tmp))
  out_df <- cbind(out_df, tmp)
}
out_df[1:3, ]

table(sub(":.+", "", names(out_df)))

my_outfile <- "plate18.csv"
#write.table(x = out_df, file = my_outfile, sep = ",", row.names = TRUE, col.names = TRUE)

#write.table(x = out_df, file = "plate18.csv", sep = ",", row.names = TRUE, col.names = TRUE)
#write.table(x = out_df, file = "plate17.csv", sep = ",", row.names = TRUE, col.names = TRUE)
#write.table(x = out_df, file = "plate_parental.csv", sep = ",", row.names = TRUE, col.names = TRUE)
#write.table(x = out_df, file = "plate6.csv", sep = ",", row.names = TRUE, col.names = TRUE)
#write.table(x = out_df, file = "plate7.csv", sep = ",", row.names = TRUE, col.names = TRUE)
#write.table(x = out_df, file = "plate8.csv", sep = ",", row.names = TRUE, col.names = TRUE)
#write.table(x = out_df, file = "plate9.csv", sep = ",", row.names = TRUE, col.names = TRUE)
#write.table(x = out_df, file = "plate10.csv", sep = ",", row.names = TRUE, col.names = TRUE)
#write.table(x = out_df, file = "plate11.csv", sep = ",", row.names = TRUE, col.names = TRUE)
#write.table(x = out_df, file = "plate12.csv", sep = ",", row.names = TRUE, col.names = TRUE)
#write.table(x = out_df, file = "plate13.csv", sep = ",", row.names = TRUE, col.names = TRUE)
#write.table(x = out_df, file = "plate14.csv", sep = ",", row.names = TRUE, col.names = TRUE)
#write.table(x = out_df, file = "plate5.csv", sep = ",", row.names = TRUE, col.names = TRUE)
```



